package application;

import javafx.fxml.FXML;
import javafx.geometry.HPos;

import java.util.ArrayList;

import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.control.ComboBox;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.text.Text;

public class MewTwoLayoutController {
	@FXML
	private GridPane calPane;

	@FXML
	private Circle c1;
	@FXML
	private Circle c2;
	@FXML
	private Circle c3;

	private ArrayList<Circle> circle_list = new ArrayList<Circle>();
	int y = 131;
	int x = 166;

	public void initialize() {
		GridPane.setHalignment(calPane, HPos.CENTER);
		for (int j = 1; j <= calPane.getRowCount(); j++) {
			for (int i = 1; i <= calPane.getColumnCount(); i++) {
				if ((i * j) <= 31) {
					Text tempDay = new Text(Integer.toString(i * j));
					GridPane.setHalignment(tempDay, HPos.CENTER);
					calPane.add(tempDay, i - 1, j - 1);
				} else {
					i = calPane.getColumnCount() + 2;
					j = calPane.getRowCount() + 2;
					break;
				}
			}
		}
		c1.setVisible(false);
		c2.setVisible(false);
		c3.setVisible(false);
	}

	// Event Listener on Button.onAction
	@FXML
	public void getComboBoxInfo(ActionEvent event) {
		// TODO Autogenerated

	}

	@FXML
	public void deleteCircles(ActionEvent event) {
		c1.setVisible(false);
		c2.setVisible(false);
		c3.setVisible(false);
		
		for(Circle circ : circle_list) {
			circ.setVisible(false);
		}
	}

	@FXML
	public void drawCircles(ActionEvent event) {
		c1.setVisible(true);
		c2.setVisible(true);
		c3.setVisible(true);
		
		for(Circle circ : circle_list) {
			circ.setVisible(true);
		}
	}

	@FXML
	public void drawNewCircle(MouseEvent event) {
		try {
			Node clickedNode = event.getPickResult().getIntersectedNode();
			int col = GridPane.getColumnIndex(clickedNode);
			int row = GridPane.getRowIndex(clickedNode);
			System.out.println("Row: " + (row + 1) + " Col: " + (col + 1));
			Circle c = new Circle();
			GridPane.setHalignment(c, HPos.LEFT);
			Color color = Color.web("0x009eff");
			c.setRadius(7);
			c.setFill(color);
			c.setVisible(true);
			GridPane.setColumnIndex(c, col);
			GridPane.setRowIndex(c, row);
			System.out.println(c.getCenterX());
			System.out.println(c.getCenterY());
			calPane.getChildren().add(c);
			
			circle_list.add(c);
		} catch (Exception err) {
			System.out.println(err);
			System.out.println("Missed the box");
		}

	}
}
