package application;

import javafx.fxml.FXML;
import javafx.geometry.HPos;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import javafx.scene.layout.GridPane;
import javafx.scene.text.Text;

public class MewTwoLayoutController {
	@FXML
	private GridPane calPane;
	public void initialize(){
		GridPane.setHalignment(calPane, HPos.CENTER);
		for(int j = 1; j <= calPane.getRowCount(); j++) {
		for(int i = 1; i <= calPane.getColumnCount(); i++) {
				if((i*j) <= 31) {
					Text tempDay = new Text(Integer.toString(i * j));
				
					calPane.add(tempDay, i-1, j-1);
				} else {
					i = calPane.getColumnCount() + 2;
					j = calPane.getRowCount() + 2;
					break;
				}
			}
		}
		
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void getComboBoxInfo(ActionEvent event) {
		// TODO Autogenerated
		
	}
}
