package application;

import javafx.fxml.FXML;
import javafx.geometry.HPos;

import java.util.ArrayList;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import javafx.scene.layout.GridPane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.text.Text;

public class MewTwoLayoutController {
	@FXML
	private GridPane calPane;
	private ArrayList<Circle> circle_list = new ArrayList<Circle>();
	int y = 131;
	int x = 166;
	public void initialize(){
		GridPane.setHalignment(calPane, HPos.CENTER);
		for(int j = 1; j <= calPane.getRowCount(); j++) {
		for(int i = 1; i <= calPane.getColumnCount(); i++) {
				if((i*j) <= 31) {
					Text tempDay = new Text(Integer.toString(i * j));
				
					calPane.add(tempDay, i-1, j-1);
				} else {
					i = calPane.getColumnCount() + 2;
					j = calPane.getRowCount() + 2;
					break;
				}
			}
		}
		
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void getComboBoxInfo(ActionEvent event) {
		// TODO Autogenerated
		
	}
	@FXML
	public void deleteCircles(ActionEvent event) {
		for(Circle c : circle_list) {
			calPane.getChildren().remove(c);
		}
		circle_list.clear();
	}
	@FXML
	public void drawCircles(ActionEvent event) {
		Circle circle1 = new Circle();
		int radius = 7;
		circle1.setCenterX(x);
		circle1.setCenterY(y);
		circle1.setRadius(radius);
		Color one = Color.web("0xff0000");
		circle1.setFill(one);
		calPane.getChildren().add(circle1);
		
		Circle circle2 = new Circle();
		x+=60;
		circle2.setCenterX(x);
		circle2.setCenterY(y);
		circle2.setRadius(radius);
		Color two = Color.web("0x009eff");
		circle1.setFill(two);		
		calPane.getChildren().add(circle2);
		
		Circle circle3 = new Circle();
		x+=60;
		circle3.setCenterX(x);
		circle3.setCenterY(y);
		circle3.setRadius(radius);
		Color three = Color.web("0x00ff1a");
		circle1.setFill(three);
		calPane.getChildren().add(circle3);
		
		circle_list.add(circle1);
		circle_list.add(circle2);
		circle_list.add(circle3);
	}
}
